spring:
  application:
    name: gym-crm
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate  # Safer default for production
#      jakarta:
#        persistence:
#          sql-load-script-source: META-INF/import.sql
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

application:
  security:
    jwt:
      secret-key: "48656c6c6f2c2068656c6c6f206d79206e616d65206973204967726973303034"
      expiration: 1800000 # 30 minutes (for deployment)
      refresh-token:
        expiration: 15552000000 # 6 months (for deployment)

  active_mq:
    broker:
      destination: "trainer.workload.queue"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  instance:
    hostname: gym-crm
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://gym-crm-service-discovery:8765/eureka/
    fetch-registry: true
    register-with-eureka: true
