spring:
  application:
    name: trainer-session-management
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

server:
  port: 8766

eureka:
  instance:
    hostname: trainer-session-management
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://gym-crm-service-discovery:8765/eureka/
    fetch-registry: true
    register-with-eureka: true

application:
  security:
    jwt:
      secret-key: "48656c6c6f2c2068656c6c6f206d79206e616d65206973204967726973303034"

  broker:
    destination: "trainer.workload.queue"