spring:
  application:
    name: trainer-session-management
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://trainer_session:s3cr3tp455w0rd@mongodb:27017/trainer_session_db?authSource=admin
      username: trainer_session
      password: s3cr3tp455w0rd
      database: trainer_session_db
      auto-index-creation: true

server:
  port: 8766

eureka:
  instance:
    hostname: trainer-session-management
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://gym-crm-service-discovery:8765/eureka/
    fetch-registry: true
    register-with-eureka: true

application:
  broker:
    destination: "trainer.workload.queue"